org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
# Memaksa Gradle memakai JDK 17 (Temurin) yang kompatibel dengan AGP 8.11.1
org.gradle.java.home=C:/Users/ADMIN/jdk17/jdk-17.0.14+7
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
